### PR TITLE
Define the /reserves endpoint

### PR DESCRIPTION
**Pull request by plamut**
Towards https://github.com/tradingstrategy-ai/backend/issues/116
Related backend implementation PR: https://github.com/tradingstrategy-ai/backend/pull/115

> **Warning**
> Response schema is not finalized yet

### CODE REVIEW

**Comment by kenkunz** [comment]
@plamut sorry I wasn't able to review this sooner – was knee-deep in some `frontend` updates.

If it's not too late for the `v1`, I would suggest adding `protocol_slug` to `ReserveInfo`. I realize it's a query param so all the results will be related to the same protocol, but it's possible this may change in the future (ability to query reserves across protocols by some other param?). It can also make things easier / cleaner when all of the relevant identifying attributes of an entity are available on that entity's schema.

**Comment by kenkunz** [comment]
@plamut are there any summary-level (aggregate) financial metrics that can be added to `ReserveInfo`?

I assume we'll have more info available on the reserve details API… but having some summary metrics available on the index can be quite helpful when users are scanning entities in a table, sorting, etc.

**Comment by kenkunz** [comment]
@plamut since this API includes pagination, I will need to rely on the backend for sorting.

For the `v1`, it may be sufficient to just have a sensible default sort – probably `reserve_slug`. As long as I can count on deterministic ordering of some kind.

If/when we do add sort options, follow the conventions of other `backend` APIs with `sort` and `direction` params.

**Comment by kenkunz** [comment]
@plamut one last comment 😄 

The `frontend` issue tradingstrategy-ai/frontend#211 assumes that we'll have an index view for _all_ reserves, not just those for a single protocol. This won't really matter initially, since we'll only have `AAVE` to start… but it might be nice if the API didn't _require_ the `protocol_slug` param.

**Comment by plamut** [comment]
@kenkunz Thanks for the comments!

No, nothing is too late, as the implementation has not been merged yet. Everything sounds quite straightforward, except for the aggregate financial metrics. It would be good to know what exactly do we want to present, as providing aggregate stats usually requires non-trivial work.

We can discuss this tomorrow in the backlog dig through.

**Comment by plamut** [comment]
> @plamut one last comment smile
> 
> The `frontend` issue [tradingstrategy-ai/frontend#211](https://github.com/tradingstrategy-ai/frontend/issues/211) assumes that we'll have an index view for _all_ reserves, not just those for a single protocol. This won't really matter initially, since we'll only have `AAVE` to start… but it might be nice if the API didn't _require_ the `protocol_slug` param.

I'd say let's address this when the time comes. On the backend, AAVE v3 protocol is _very_ hardcoded right now in the endpoint (e.g. reading from dedicated DB tables for AAVE v3), thus making the endpoint more "general" would require implementing a fake "generic" facade with little current value (not that much, but still some...).

Also, making a required parameter optional in the future will not break anything, thus I would skip this for now, unless there would already be clear benefits for the frontend?

If so, please let me know and I will add it to v1.

**Pull request merged**
